#!/bin/bash
command=$1
if [[ $command != import && $command != export ]]; then
    echo "Usage: update <import|export>"
    return 1
fi
filebrowser config $command "$(basename $BASH_SOURCE)/config.json" &&
filebrowser users $command "$(basename $BASH_SOURCE)/users.json"
