#!/bin/bash
command=$1
if [[ $command != import && $command != export ]]; then
    echo "Usage: update <import|export>"
    exit
fi
filebrowser config $command "$(dirname $BASH_SOURCE)/config.json" &&
filebrowser users $command "$(dirname $BASH_SOURCE)/users.json"
